# default: &default
#   adapter: mysql2
#   charset: utf8mb4
#   encoding: utf8
#   pool: 5
#   username: <%= ENV['RAILS_DATABASE_USERNAME'] %>
#   password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
#   host: <%= ENV['RAILS_DATABASE_HOST'] %>
#   port: <%= ENV['RAILS_DATABASE_PORT'] %>
#   socket:   "/tmp/mysql.sock"

# development:
#   <<: *default
#   database: app_development

# test:
#   <<: *default
#   database: app_test

# production:
#   <<: *default
#   database: app_production


# development:
#   adapter: mysql2
#   database: app_development
#   charset: utf8mb4
#   collation: utf8mb4_bin
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   host: <%= ENV.fetch("MYSQL_HOST") { 'db' } %>
#   username: <%= ENV.fetch("MYSQL_USERNAME") { 'root' } %>
#   password: <%= ENV.fetch("MYSQL_PASSWORD") { 'password' } %>

test:
  adapter: mysql2
  database: app_test
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DATABASE_USER") { 'root' }  %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' }  %>
  socket:   "/var/lib/mysql/mysql.sock"







# test:
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#   database: db/development.sqlite3
