##### 本番環境RDS用 #####

default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8
  pool: 5
  host:     "terraform-rds.cwmmfqrwq6x1.ap-northeast-1.rds.amazonaws.com"
  database: "app_development"
  username: "test"
  password: "password"
  socket:   "/tmp/mysql.sock"
  port: "3306"


development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
