default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['RAILS_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
  host: <%= ENV['RAILS_DATABASE_HOST'] %>
  port: <%= ENV['RAILS_DATABASE_PORT'] %>
  socket:   "/tmp/mysql.sock"

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production


# development:
#   adapter: mysql2
#   charset: utf8mb4
#   collation: utf8mb4_bin
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   host: <%= ENV.fetch("MYSQL_HOST") { 'db' } %>
#   username: <%= ENV.fetch("MYSQL_USERNAME") { 'root' } %>
#   password: <%= ENV.fetch("MYSQL_PASSWORD") { 'password' } %>




